## Configuration for the from Snakemake workflow.

# sample name, pointing to STARsolo output directory (same as the ""--outFileNamePrefix" input for STAR)
#TODO: add sample_sheet read-ins as an option for passing sample lists
Samples:
  # Heart_Control:
  # SH6:
  # SH7:
  # uSH8:
  T2V_GRCm39:
  # SH9:

# .fasta (genome sequence) and .gtf (gene annotations) files used to build STAR reference
## Mouse
GENOME_FASTA: /workdir/dwm269/genomes/mm39_all/GENCODE_M31/GRCm39.genome.fa
GENES_GTF: /workdir/dwm269/genomes/mm39_all/GENCODE_M31/gencode.vM31.annotation.gtf

# directory where STARsolo outputs are stored - be sure to use an absolute path (starting with root)
DATADIR: /workdir/dwm269/totalRNA/STRS-HD/data/align_out_rRNA2

# directory for temporary files
TMPDIR: ./tmp

########################################################################################################
# Executables - file paths
########################################################################################################
SAMTOOLS_EXEC: /programs/samtools-1.15.1-r/bin/samtools
UMITOOLS_EXEC: umi_tools
QUALIMAP_EXEC: qualimap
PICARD: /home/dwm269/miniconda3/envs/scTAR1.2/share/picard-2.18.29-0/picard.jar
DROPSEQ: /home/dwm269/miniconda3/envs/scTAR1.2/share/dropseq_tools-2.4.0-1
GTFTOGENEPRED: /home/dwm269/miniconda3/envs/scTAR1.2/bin/gtfToGenePred # used to convert gtf to reFflat format, not needed if annotation is in reFflat
# BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored

CORES: 18 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")

MERGEBP: 500 #default 500 (Note- window size across genome is 50bp)
THRESH: 2500000 #default 10000000
