## Configuration for the from Snakemake workflow.

# sample name, pointing to STARsolo output directory (same as the ""--outFileNamePrefix" input for STAR)
#TODO: add sample_sheet read-ins as an option for passing sample lists
Samples:
  Heart_Control:
  SHVN1:
  T2V:
  SHVN2:

# .fasta (genome sequence) and .gtf (gene annotations) files used to build STAR reference
## Mouse
GENOME_FASTA: /workdir/dwm269/genomes/mm39_all/GENCODE_M31/GRCm39.genome.fa
GENES_GTF: /workdir/dwm269/genomes/mm39_all/GENCODE_M31/gencode.vM31.annotation.gtf

# directory where STARsolo outputs are stored - be sure to use an absolute path (starting with root)
DATADIR: /workdir/dwm269/STRS-HD/data/out

# directory for temporary files
TMPDIR: ./tmp

########################################################################################################
# Run settings
########################################################################################################

# BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored

CORES: 20 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")

MERGEBP: 500 #default 500 (Note- window size across genome is 50bp)
THRESH: 2500000 #default 10000000
